#!/bin/bash

sudo wget -O /usr/local/bin/trsh https://raw.githubusercontent.com/Adeyomola/recycle_bin/main/trsh
sudo chmod +x /usr/local/bin/trsh

sudo su - -c "sed -in '/count-autodelete/d' /etc/anacrontab"
sudo su - -c 'echo "1       10      count-autodelete        trsh -c" >> /etc/anacrontab'
