#!/bin/bash
#wget
if [[ -f /usr/local/bin/trsh ]]
then
echo "trash already exists"
else
sudo cp ./trsh /usr/local/bin
sudo chmod +x /usr/local/bin/trsh
fi

sudo su - -c "sed -in '/count-autodelete/d' /etc/anacrontab"
sudo su - -c 'echo "1       10      count-autodelete        trsh -c" >> /etc/anacrontab'
