#!/bin/bash

#checks if /trash directory exists
if [[ -d /trash ]]
then
:
else
( sudo mkdir /trash ) #creates /trash directory if it doesn't exist
fi

#checks if /trash/.metadata directory exists
if [[ -d /trash/.metadata ]]
then
:
else
( sudo mkdir /trash/.metadata; sudo chmod o+w /trash/.metadata ) #creates metadata directory if it doesn't exist
fi

#checks if metadata_count directory exists
if [[ -d /trash/.metadata_count ]]
then
:
else
( sudo mkdir /trash/.metadata_count; sudo chmod o+w /trash/.metadata_count ) #creates writeable metadata_count directory
fi


#define positional arguments and variables
arg1=$1 #argument 1 - indicates whether you intend to delete or restore a file
arg2=$2 #argument 2 - indicates the file
arg3=$( sudo stat $arg2 | awk 'NR==3{print $4}' ) #argument 3 - the file's inode
wd=$( pwd ) #working directory/the file's directory of origin

#delete function
function delete() {
if [[ $( pwd ) == /trash ]]
then
:
elif [[ $arg2 == '' ]]
then
echo "Insufficient argument. Please specify a file."
elif [[ -e /trash/$arg2 ]]
then
echo "Filename already exists in the trash. Please rename the file and try again"
#( sudo echo $wd > /trash/.metadata/${arg3} )
#( sudo echo 1 > /trash/.metadata_count/${arg3} )
#( sudo mv -i "$arg2" /trash/${arg2%.*}$(( count )).${arg2#*.} )
else
( sudo echo $wd > /trash/.metadata/${arg3} )
( sudo echo 1 > /trash/.metadata_count/${arg3} )
( sudo mv -i "$arg2" /trash )
echo "${arg2} has been moved to trash."
fi
}

#restore function
function restore() {
if [[ $arg2 == '' ]]
then
echo "Insufficient argument. Please specify a file."
else
( sudo mv -i ${arg2} $( cat /trash/.metadata/${arg3} ) )
( sudo rm /trash/.metadata/${arg3} )
( sudo rm /trash/.metadata_count/${arg3} )

if [[ -f /trash/${arg2} ]]
then
echo "{arg2} was not restored."
else
echo "${arg2} has been restored."
fi

fi
}

#counter
function counter() {
if [[ $( ls -A /trash/.metadata_count ) ]] #checks if the directory is not empty
then
for i in /trash/.metadata_count/*
do
arg4=$( sudo find / -xdev -inum ${i##*/} )
echo $(( $( cat $i ) + 1 )) > $i

if [[ $( cat $i ) == 31 ]] #deletes the files after 30 days
then
( sudo rm -dr $arg4 ) #command retrieves filename using inode
( sudo rm "${i}" ) #removes metadata_count file corresponding to the file
( sudo rm /trash/.metadata/${i##*/} ) #removes metadata file (directory data) corresponding to the file
fi
done
else #if the directory is empty, do nothing
:
fi
}

function help() { echo -e "Usage: \n trsh [OPTION] [FILE] \n\n -d -- Move file to trash \n -r -- Restore file to its original directory (use this option from the /trash directory) \n -h, --help -- Display this help \n"
}

#case switch
case $arg1 in
"-d")
delete;;
"-r")
restore;;
"-c")
counter;;
"-h" | "--help")
help;;
esac

#null option
if [[ "$1" =~ [^-cdhr] && ! "$1" =~ (--help)  ]]
then
echo "Invalid argument. Check trsh -h."
fi
